[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
maturin = "^1.8.1"

[build-system]
requires = ["maturin>=1.4.0"]
build-backend = "maturin"

[project]
name = "shazamio_core"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
bindings = "pyo3"
